// en-GB: Creates controlled homologation seed data so local validation uses a repeatable database state.
/* global console, process */

import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client.js";
import {
  buildHomologationFixturePlan,
  homologationReferenceFilters,
  parseHomologationActivityCount
} from "./homologation-fixtures.mjs";

const connectionString = process.env.DATABASE_URL;
const adminEmail = process.env.E2E_EMAIL?.trim();
const volume = parseHomologationActivityCount(process.env.HOMOLOGATION_ACTIVITY_COUNT);

if (!connectionString) {
  throw new Error("DATABASE_URL is required to run the homologation seed.");
}
if (!adminEmail) {
  throw new Error("E2E_EMAIL is required to resolve the tenant-scoped homologation owner.");
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString })
});

async function main() {
  const company = await prisma.company.findFirstOrThrow({
    where: { name: "ShiftFlow Integration Company", deletedAt: null }
  });
  const references = homologationReferenceFilters(company.id, adminEmail);
  const [client, team, shift, admin, analyst] = await Promise.all([
    prisma.client.findFirstOrThrow({ where: references.client }),
    prisma.team.findFirstOrThrow({ where: references.team }),
    prisma.shift.findFirstOrThrow({ where: references.shift }),
    prisma.user.findFirstOrThrow({ where: references.admin }),
    prisma.user.findFirstOrThrow({ where: references.analyst })
  ]);

  const now = new Date();
  const existing = await prisma.activity.findMany({
    where: {
      companyId: company.id,
      title: { startsWith: "Homologation volume activity " }
    },
    select: { id: true, title: true }
  });
  const activities = [];
  let updatedActivities = 0;

  for (const fixture of buildHomologationFixturePlan(existing, now, volume)) {
    const data = {
      companyId: company.id,
      clientId: client.id,
      teamId: team.id,
      shiftId: shift.id,
      assigneeId: analyst.id,
      reporterId: admin.id,
      title: fixture.title,
      description: "STATE-07 homologation volume fixture activity.",
      requested: `Homologation request ${fixture.index} for operational validation.`,
      performed: "Fixture triage completed by homologation seed.",
      inProgressDetail:
        fixture.status === "IN_PROGRESS"
          ? "Homologation execution is in progress."
          : "No active execution at this stage.",
      pendingDetail:
        fixture.status === "DONE"
          ? "No pending homologation action."
          : "Pending follow-up from the next operational update.",
      finalizationDetail:
        fixture.status === "DONE"
          ? "Homologation item finalised."
          : "Finalisation is not available yet.",
      observations: "Generated by STATE-07 homologation seed with complete operational fields.",
      systemName: fixture.systemName,
      serviceName: fixture.serviceName,
      status: fixture.status,
      priority: fixture.priority,
      slaDueAt: fixture.slaDueAt,
      startedAt: fixture.startedAt,
      completedAt: fixture.completedAt,
      deletedAt: null,
      createdAt: fixture.createdAt,
      updatedAt: fixture.createdAt,
      createdById: admin.id,
      updatedById: admin.id
    };
    if (fixture.existingId) {
      const { companyId: _companyId, title: _title, createdAt: _createdAt, ...updateData } = data;
      void _companyId;
      void _title;
      void _createdAt;
      await prisma.activity.update({ where: { id: fixture.existingId }, data: updateData });
      updatedActivities += 1;
    } else {
      activities.push(data);
    }
  }

  if (activities.length > 0) {
    await prisma.activity.createMany({ data: activities });
  }

  await prisma.activity.updateMany({
    where: {
      companyId: company.id,
      title: { startsWith: "Homologation volume activity " },
      requested: null
    },
    data: {
      requested: "Homologation request for operational validation.",
      performed: "Fixture triage completed by homologation seed.",
      inProgressDetail: "Execution state follows the activity status.",
      pendingDetail: "Pending follow-up from the next operational update.",
      finalizationDetail: "Finalisation depends on the current activity status.",
      observations: "Backfilled by STATE-07 homologation seed with complete operational fields.",
      serviceName: "Operational support"
    }
  });

  const totalHomologationActivities = await prisma.activity.count({
    where: {
      companyId: company.id,
      title: { startsWith: "Homologation volume activity " },
      deletedAt: null
    }
  });
  const totalActivities = await prisma.activity.count({
    where: { companyId: company.id, deletedAt: null }
  });

  console.log(
    JSON.stringify(
      {
        status: "ok",
        createdActivities: activities.length,
        updatedActivities,
        totalHomologationActivities,
        totalActivities
      },
      null,
      2
    )
  );
}

try {
  await main();
} finally {
  await prisma.$disconnect();
}
